In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('../data/train.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240000 entries, 0 to 239999
Data columns (total 23 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   id                          240000 non-null  int64
 1   titulo                      234613 non-null  object
 2   descripcion                 238381 non-null  object
 3   tipodepropiedad             239954 non-null  object
 4   direccion                   186928 non-null  object
 5   ciudad                      239628 non-null  object
 6   provincia                   239845 non-null  object
 7   antiguedad                  196445 non-null  float64
 8   habitaciones                217529 non-null  float64
 9   garages                     202235 non-null  float64
 10  banos                       213779 non-null  float64
 11  metroscubiertos             222600 non-null  float64
 12  metrostotales               188533 non-null  float64
 13  idzona                      211379 non-null  float64
 14  lat                         116512 non-null  float64
 15  lng                         116512 non-null  float64
 16  fecha                       240000 non-null  object
 17  gimnasio                    240000 non-null  float64
 18  usosmultiples               240000 non-null  float64
 19  piscina                     240000 non-null  float64
 20  escuelascercanas            240000 non-null  float64
 21  centroscomercialescercanos  240000 non-null  float64
 22  precio                      240000 non-null  float64
dtypes: float64(15), int64(1), object(7)
memory usage: 42.1+ MB

In [4]:
df.describe()

,id,antiguedad,habitaciones,garages,banos,metroscubiertos,metrostotales,idzona,lat,lng,gimnasio,usosmultiples,piscina,escuelascercanas,centroscomercialescercanos,precio
count,240000.000000,196445.000000,217529.000000,202235.000000,213779.000000,222600.000000,188533.000000,2.113790e+05,116512.000000,116512.000000,240000.000000,240000.000000,240000.000000,240000.000000,240000.000000,2.400000e+05
mean,149969.382092,8.116114,2.902326,1.546874,2.132417,174.016774,176.765145,2.423468e+06,20.696818,-99.509221,0.062475,0.055092,0.087383,0.444142,0.396533,2.530838e+06
std,86634.579744,9.553830,0.896894,0.853507,0.912546,98.152950,94.427328,1.056794e+07,3.137884,9.744143,0.242017,0.228160,0.282397,0.496871,0.489179,2.152552e+06
min,1.000000,0.000000,1.000000,0.000000,1.000000,15.000000,15.000000,2.200000e+01,-100.886679,-125.859375,0.000000,0.000000,0.000000,0.000000,0.000000,3.100000e+05
25%,74930.750000,0.000000,2.000000,1.000000,1.000000,90.000000,102.000000,2.489000e+04,19.359846,-100.977908,0.000000,0.000000,0.000000,0.000000,0.000000,9.527725e+05
50%,149875.500000,5.000000,3.000000,2.000000,2.000000,153.000000,155.000000,5.638300e+04,19.543273,-99.240387,0.000000,0.000000,0.000000,0.000000,0.000000,1.850000e+06
75%,225016.500000,10.000000,3.000000,2.000000,3.000000,240.000000,238.000000,8.783800e+04,20.740005,-99.134777,0.000000,0.000000,0.000000,1.000000,1.000000,3.390000e+06
max,299999.000000,80.000000,10.000000,3.000000,4.000000,439.000000,439.000000,5.000400e+07,83.026219,121.036000,1.000000,1.000000,1.000000,1.000000,1.000000,1.252500e+07

# Hay entradas que no tienen la antiguedad/habs/garages/banos/mtrscub/mtrstot

In [5]:
print('sin antiguedad\t', df[df['antiguedad'].isnull()]['id'].count())
print('sin habs\t', df[df['habitaciones'].isnull()]['id'].count())
print('sin garages\t', df[df['garages'].isnull()]['id'].count())
print('sin banos\t', df[df['banos'].isnull()]['id'].count())
print('sin metroscub\t', df[df['metroscubiertos'].isnull()]['id'].count())
print('sin metrostot\t', df[df['metrostotales'].isnull()]['id'].count())

sin antiguedad	 43555
sin habs	 22471
sin garages	 37765
sin banos	 26221
sin metroscub	 17400
sin metrostot	 51467

# Casos raros a tener en cuenta o sacar

## Entradas con 10 habitaciones
Algunas tienen sentido y otras no tanto, 10 hab en 20 mts cubiertos no por ejemplo

In [6]:
df[df['habitaciones']==10].describe()

,id,antiguedad,habitaciones,garages,banos,metroscubiertos,metrostotales,idzona,lat,lng,gimnasio,usosmultiples,piscina,escuelascercanas,centroscomercialescercanos,precio
count,316.000000,296.000000,316.0,206.000000,107.000000,193.000000,264.000000,3.030000e+02,170.000000,170.000000,316.000000,316.000000,316.000000,316.000000,316.000000,3.160000e+02
mean,148412.920886,16.533784,10.0,1.126214,2.785047,303.803109,253.859848,2.045091e+06,20.038185,-99.548744,0.012658,0.037975,0.009494,0.563291,0.500000,4.520162e+06
std,87993.297705,13.387024,0.0,1.092588,1.099125,96.587248,91.627486,9.755307e+06,2.372238,8.127872,0.111972,0.191438,0.097126,0.496765,0.500793,2.735238e+06
min,592.000000,0.000000,10.0,0.000000,1.000000,20.000000,20.000000,3.520000e+03,0.000000,-110.307073,0.000000,0.000000,0.000000,0.000000,0.000000,3.800000e+05
25%,69655.500000,5.000000,10.0,0.000000,2.000000,250.000000,191.500000,2.415500e+04,19.369950,-101.167447,0.000000,0.000000,0.000000,0.000000,0.000000,2.500000e+06
50%,140853.000000,14.500000,10.0,1.000000,3.000000,322.000000,245.000000,5.567200e+04,19.455938,-99.192391,0.000000,0.000000,0.000000,1.000000,0.500000,3.950000e+06
75%,227402.500000,20.000000,10.0,2.000000,4.000000,380.000000,324.250000,7.853500e+04,20.649123,-99.097485,0.000000,0.000000,0.000000,1.000000,1.000000,5.500000e+06
max,297391.000000,80.000000,10.0,3.000000,4.000000,435.000000,435.000000,5.000400e+07,28.638967,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.250000e+07

### Este es re raro, se ve que en realidad son 5 deptos en uno, por qué se vende como casa?
Además tiene de interesante que en la descripción dice la cantidad de mtrs totales (dato faltante), se podría utilizar las descripciones para sacar algunos datos?

In [7]:
pd.set_option('display.max_colwidth', None)
df[(df['habitaciones']==10) & (df['metroscubiertos']==435)]

,id,titulo,descripcion,tipodepropiedad,direccion,ciudad,provincia,antiguedad,habitaciones,garages,...,idzona,lat,lng,fecha,gimnasio,usosmultiples,piscina,escuelascercanas,centroscomercialescercanos,precio
210913,9210,"50) casa en venta en isidro fabela, tlalnepantla de baz","<p>venta de casa de 223m2 de terreno y 435m2 de construcci&oacute;n. casa con 5 departamentos independientes, cuenta cada uno con 2 rec&aacute;maras, sala, comedor, cocina integral, 1 ba&ntilde;o, &aacute;rea de lavado en azotea y lugar de estacionamiento para 2 autos. cerca de avenidas principales, escuelas y trasporte p&uacute;blico. referencia: 8701/ 50</p>",Casa,ISIDRO FABELA,Tlalnepantla de Baz,Edo. de México,28.0,10.0,2.0,...,56282.0,19.581042,-99.19302,2014-01-06 00:00:00,0.0,0.0,0.0,1.0,1.0,2750000.0

## Descripciones de entradas con metros faltantes

In [8]:
df[df['metrostotales'].isnull()][['descripcion']]

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       descripcion
8                                                                                                                                                                                                <p>pre-venta de preciosos departamento ecologicos &nbsp;se ejerce con subsidio de 62,000; sala, comedor, cocina con &nbsp;tarja &nbsp;y azulejo con cenefa decorativa en cocina con barra desayunador, patio de servicio, 2 recamaras, 1 ba&ntilde;o, protecciones en puertas y ventanas cajon designado de estacionamiento, &nbsp;enjarre general en toda la vivienda. acabados finos.&nbsp;</p>
9                                                                                    terreno de 5.500m2 bardeado, uso de suelo h-200-a, plano de forma irregular colinda al norte con circuito exterior mexiquense con 122m2, al oriente con 21m2 sobre una de las vías más importantes de ixtapaluca la av. morelos y gasolinera con 42m2.al sur con 105m2 con calle cerrada que le da acceso al terreno, el cuarto lado al poniente con 57m2 colinda con campo cuenta con una nave industrial con superficie aproximada a 1.890 m2 y construcción aproximada a 250m2 de una planta como oficinas
10                                                                                                                                                                                                                                                                                                                                                                                                              <p>mi 2&deg; credito<br />para todos aquellos trabajadores que ya tuvieron su primer credito por el infonavit y terminaron de pagarlo.<br />tienes derecho a tu 2&deg; credito</p>
11                                                                                                                                                                          departamento nuevo ,256 m2 de construccion,un departamento por piso,acabados de lujo,elevador directo a tu departamento,elevador de servicio,cocina integral ,lavavajillas, ,boliler,clinas con 5 aparatos, ilumimacion natural ,espejos ,,1 bodegas,dos cajones de estacinamiento ,vista panoramica,amenidades alberca,jacuzzi,salon   de eventos,ginmasio,sala de juntas, vigilancia 24 hrs ,camara de seguridad $7;
24                                                                                                                                                                                                                <p>propiedad en un nivel, con espacios amplios e iluminados,bardas perimetrales de 5mtscochera techada para tres autos , &nbsp;&nbsp;buen estado de conservaci&oacute;n , estudio, tres recamaras con ba&ntilde;o cada una , cocina en perfecto estado, &aacute;rea de t.v., ar&eacute;a de servicio y tendido en planta altarecamara principal con jacuzzie.</p>\r\n<p>c721</p>
...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ...
239970                                       residencia en las cañadas, una gran oportunidad para poder remodelar una casa cerca del club de golf. cuenta con cinco recamaras. una de ellas en la planta baja, con pequeña cocineta y baño completo. las otras tres recamaras se encuentran en la planta alta y hay la principal con baño y las otras dos con baño completo en el corredor. \ncuenta con un muy amplio jardín, y bonita terraza, cocina abierta hacia el comedor y vistas al jardín. cuenta con un cuarto al nivel del jardín con su baño completo. propiedad con mucho potencial.
239973                                                                                                                últimos departamentos en preventa dentro de exclusivo desarrollo con diseño arquitectónico contemporáneo y sustentable. espacios habitables desde los 65 m2. excelentes acabados. el mejor dpto en precio y calidad de la zona. desarrollo de arkeia|metropolitana. departamentos en preventa en la delegación benito juárez en zona de las colonias portales, álamos, niños héroes, nativitas, correspondencia y narvarte. - - el mejor depto precio-calidad de la zona!!!
239980                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          departamento en venta avenida palmira , san luis potosí, san luis potosí con 2 cuartos y 1.0 banos
239995  vendo casa en bosques de ica residencial a 10 minutos del centro de toluca, cuenta con 2 recamaras estacionamiento para 2 autos, sala-comedor, cocina integral, 1 baño ½, piso en toda la casa, patio trasero. vigilancia las 24 horas. \naceptamos todo tipo de creditos: infonavit total, cofinavit, fovissste, contado, bancario. \ncasas para entrega inmediata. \n\nno dude en contactarme para proporcionarle más información, enviarle más fotografías y plano de ubicación del desarrollo, o programar una cita sin compromiso. \nsonia velazquez bernal cel:  nextel: 523880 id.
239999                                                                                                                                                                                                                                           id:19816, muy bonito e iluminado departamento, con excelente distribucion. la recamara principal con balcón y el edificio muy moderno, cuenta con amenidades como: alberca, gym, salón de eventos y lobby. en lomas del chamizal a una cuadra de bosques y 5 min de sta. fe. col. lomas del chamizal , ave. stim . preguntar por n gaby hernandez

[51467 rows x 1 columns]

# Extraer nueva informacion de la descripcion

**TextBlob aims to provide access to common text-processing operations through a familiar interface. You can treat [TextBlob](https://textblob.readthedocs.io/en/dev/quickstart.html) objects as if they were Python strings that learned how to do Natural Language Processing.**

In [41]:
# pip install -U textblob
# python -m textblob.download_corpora
from textblob import TextBlob

text = '''
The titular threat of The Blob has always struck me as the ultimate movie
monster: an insatiably hungry, amoeba-like mass able to penetrate
virtually any safeguard, capable of--as a doomed doctor chillingly
describes it--"assimilating flesh on contact.
Snide comparisons to gelatin be damned, it's a concept with the most
devastating of potential consequences, not unlike the grey goo scenario
proposed by technological theorists fearful of
artificial intelligence run rampant.
'''

blob = TextBlob(text)

print(blob.tags[:4], '...')

print(blob.noun_phrases[:4], '...')

for sentence in blob.sentences:
    print(sentence.sentiment.polarity)

[('The', 'DT'), ('titular', 'JJ'), ('threat', 'NN'), ('of', 'IN')] ...
['titular threat', 'blob', 'ultimate movie monster', 'amoeba-like mass'] ...
0.06000000000000001
-0.34166666666666673

**Decodificar los html entities de las descripciones**

In [65]:
import html

desc = df[df['metrostotales'].isnull()]['descripcion'].iloc[1]

print('antes del unescape:\n', desc, '\n')
desc = html.unescape(desc) #esto habria que hacerlo con todas las descripciones y borrar los <p>, etc
print('despues:\n', desc, '\n')

antes del unescape:
 terreno de 5.500m2 bardeado, uso de suelo h-200-a, plano de forma irregular colinda al norte con circuito exterior mexiquense con 122m2, al oriente con 21m2 sobre una de las vías más importantes de ixtapaluca la av. morelos y gasolinera con 42m2.al sur con 105m2 con calle cerrada que le da acceso al terreno, el cuarto lado al poniente con 57m2 colinda con campo cuenta con una nave industrial con superficie aproximada a 1.890 m2 y construcción aproximada a 250m2 de una planta como oficinas

despues:
 terreno de 5.500m2 bardeado, uso de suelo h-200-a, plano de forma irregular colinda al norte con circuito exterior mexiquense con 122m2, al oriente con 21m2 sobre una de las vías más importantes de ixtapaluca la av. morelos y gasolinera con 42m2.al sur con 105m2 con calle cerrada que le da acceso al terreno, el cuarto lado al poniente con 57m2 colinda con campo cuenta con una nave industrial con superficie aproximada a 1.890 m2 y construcción aproximada a 250m2 de una planta como oficinas

**Paso el ejemplo por textBlob**

The sentiment property returns a namedtuple of the form Sentiment(polarity, subjectivity). The polarity score is a float within the range [-1.0, 1.0]. The subjectivity is a float within the range [0.0, 1.0] where 0.0 is very objective and 1.0 is very subjective.
El problema es que al parecer no esta entrenado para español https://github.com/sloria/TextBlob/issues/209

[Tag list](https://www.geeksforgeeks.org/python-part-of-speech-tagging-using-textblob/)

In [66]:
blob = TextBlob(desc)

print(blob.tags[:8], '...\n')

print(blob.noun_phrases, '\n')

for sentence in blob.sentences:
    print(sentence, sentence.sentiment.polarity)

[('terreno', 'NN'), ('de', 'IN'), ('5.500m2', 'CD'), ('bardeado', 'NN'), ('uso', 'FW'), ('de', 'FW'), ('suelo', 'FW'), ('h-200-a', 'NN')] ...

['5.500m2 bardeado', 'suelo h-200-a', 'forma irregular colinda', 'con circuito exterior mexiquense', 'sobre una', 'las vías más importantes', 'morelos y gasolinera', 'con 42m2.al sur', 'con calle cerrada que', 'da acceso', 'el cuarto lado', 'con campo cuenta', 'con una nave', 'industrial con superficie aproximada', 'm2 y construcción aproximada', 'una planta como oficinas']

terreno de 5.500m2 bardeado, uso de suelo h-200-a, plano de forma irregular colinda al norte con circuito exterior mexiquense con 122m2, al oriente con 21m2 sobre una de las vías más importantes de ixtapaluca la av. 0.0
morelos y gasolinera con 42m2.al sur con 105m2 con calle cerrada que le da acceso al terreno, el cuarto lado al poniente con 57m2 colinda con campo cuenta con una nave industrial con superficie aproximada a 1.890 m2 y construcción aproximada a 250m2 de una planta como oficinas 0.0